
version: '3.0'
services:
  web:
    image: olliekrk/io-lab-docker-ci-public:v0.1
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - redis
  redis:
    image: redis:6.0-rc3
    container_name: redis-prod
    ports:
      - "6379:6379"
    volumes: 
      - ../data:/data

