
version: '3.0'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    # TODO: build context, ports and redis dependency
    volumes:
      - .:/code
    environment:
      # Makes flask to reload code on change
      FLASK_ENV: development
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - redis
  redis:
    image: redis:6.0-rc4-alpine
    container_name: redis-io
    ports:
      - "6379:6379"
    volumes: 
      - "redis-data:/data"
    # TODO: missing persistence for redis. You need to persist /data directory.

volumes:
  redis-data:
